In [18]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [19]:
scalar_val = tf.Variable(123,tf.int16)
floating_val = tf.Variable(123.456,tf.float32)



In [20]:
print(scalar_val)
print(floating_val)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=123.456>


In [21]:
scalar_val_shap = tf.shape(scalar_val)
print(scalar_val_shap)
floating_val_shap = tf.shape(floating_val)
print(floating_val_shap)

tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)


In [22]:
list_tensor1 = tf.Variable([1,3,5,6],tf.int16)
print(list_tensor1)
print(tf.shape(list_tensor1))
list_tensor2 = tf.Variable([[1,2,3],[4,5,6]],tf.int16)
print(list_tensor2)
print(tf.shape(list_tensor2))
print(tf.rank(list_tensor1))
print(tf.rank(list_tensor2))

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 3, 5, 6], dtype=int32)>
tf.Tensor([4], shape=(1,), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


In [23]:
reshaped_list_tensor2 = tf.reshape(list_tensor2,[6])
print(reshaped_list_tensor2)
list_tensor3 = tf.Variable([[1,2,3,1],[1,9,10,11],[1,5,11,22],[16,17,18,19]],tf.int16)
print(list_tensor3)
print(tf.rank(list_tensor3))
print(tf.shape(list_tensor3))
reshaped_list_tensor3 = tf.reshape(list_tensor3,[2,8,1])
print(reshaped_list_tensor3)
#or like this
reshaped_list_tensor3 = tf.reshape(list_tensor3,[8,2,1])
print(reshaped_list_tensor3)
#or automatically determine the shape by only giving one dimension!
reshaped_list_tensor3 = tf.reshape(list_tensor3,[1,-1])
print(reshaped_list_tensor3)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([4 4], shape=(2,), dtype=int32)
tf.Tensor(
[[[ 1]
  [ 2]
  [ 3]
  [ 1]
  [ 1]
  [ 9]
  [10]
  [11]]

 [[ 1]
  [ 5]
  [11]
  [22]
  [16]
  [17]
  [18]
  [19]]], shape=(2, 8, 1), dtype=int32)
tf.Tensor(
[[[ 1]
  [ 2]]

 [[ 3]
  [ 1]]

 [[ 1]
  [ 9]]

 [[10]
  [11]]

 [[ 1]
  [ 5]]

 [[11]
  [22]]

 [[16]
  [17]]

 [[18]
  [19]]], shape=(8, 2, 1), dtype=int32)
tf.Tensor([[ 1  2  3  1  1  9 10 11  1  5 11 22 16 17 18 19]], shape=(1, 16), dtype=int32)


In [24]:
tensor_onefull = tf.ones([4,4,4,1])
print(tensor_onefull)
tensor_zerofull = tf.zeros([5,5])
print(tensor_zerofull)
#extracting specific values from tensors (similar to slicing in conventional programming)
tensor_sliced_onefull = tensor_onefull[0]
print(tensor_sliced_onefull)
tensor_sliced_zerofull = tensor_zerofull[0,1]
print(tensor_sliced_zerofull)

tf.Tensor(
[[[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]


 [[[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]

  [[1.]
   [1.]
   [1.]
   [1.]]]], shape=(4, 4, 4, 1), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]]], shape=(4, 4, 1), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [25]:
print(list_tensor3)
tf_slicedexampleagain = list_tensor3[0,-2:]
print(tf_slicedexampleagain)
#selecting multiple rows
tf_slicedexampleagain = list_tensor3[1::]
print(tf_slicedexampleagain)


<tf.Variable 'Variable:0' shape=(4, 4) dtype=int32, numpy=
array([[ 1,  2,  3,  1],
       [ 1,  9, 10, 11],
       [ 1,  5, 11, 22],
       [16, 17, 18, 19]], dtype=int32)>
tf.Tensor([3 1], shape=(2,), dtype=int32)
tf.Tensor(
[[ 1  9 10 11]
 [ 1  5 11 22]
 [16 17 18 19]], shape=(3, 4), dtype=int32)


In [26]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [27]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [28]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.44679457,  0.18291084, -0.30251428, -0.1914438 , -0.01479832,
         0.18445545, -0.8592036 ,  0.005288  , -0.19497217, -0.26331586]],
      dtype=float32)

In [29]:
tf.nn.softmax(predictions).numpy()

array([[0.07426739, 0.13940416, 0.08579427, 0.09587283, 0.11439624,
        0.13961965, 0.04916898, 0.11671726, 0.09553516, 0.08922405]],
      dtype=float32)

In [30]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [31]:
loss_fn(y_train[:1], predictions).numpy()

1.9688333

In [32]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [33]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2969 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1384 - accuracy: 0.9590
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1058 - accuracy: 0.9684
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0862 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0743 - accuracy: 0.9767


In [34]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0720 - accuracy: 0.9783


[0.07203935831785202, 0.9782999753952026]

In [35]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [36]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.80219928e-10, 2.23527756e-08, 2.68592601e-07, 4.28549611e-05,
        1.06095258e-10, 1.46632857e-07, 9.02622215e-13, 9.99956608e-01,
        1.81017956e-08, 1.01788956e-07],
       [1.81136729e-05, 8.06487631e-04, 9.98880804e-01, 2.69313809e-04,
        9.55256450e-14, 1.10051280e-06, 2.21336886e-05, 4.31983303e-11,
        2.03596619e-06, 2.06651558e-12],
       [5.57953911e-07, 9.98364985e-01, 3.03067587e-04, 4.44751640e-06,
        7.98925339e-06, 1.79797553e-06, 1.77203606e-06, 1.25945080e-03,
        5.57349267e-05, 2.15527862e-07],
       [9.99246716e-01, 1.50194774e-06, 3.53068172e-05, 4.42936880e-06,
        2.77974468e-05, 2.46254349e-05, 5.79660235e-04, 2.65617455e-05,
        5.73741588e-08, 5.32730810e-05],
       [1.04366100e-05, 5.70306380e-09, 5.94653284e-06, 2.97081471e-07,
        9.98002350e-01, 1.56631572e-07, 7.09898268e-06, 2.40200272e-04,
        1.71538022e-06, 1.73174753e-03]], dtype=float32)>